config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'entries/new', to: 'entries#new', as: 'new_entries'
  post 'entries', to:'entries#create'
  get 'entries/:id/edit', to: 'entries#edit', as: 'edit_entry'
  patch 'entries:id', to: 'entries#update', as: 'entry'
  delete 'entries/:id', to: 'entries#destroy', as: 'delete_entry'
  
  
  
  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :title, presence: {message: "título vacio"}
    validates :content, presence: {message: "contenido vacio"}
    validates :image_url, presence: {message: "imagen vacia"}   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :set_entries, only: [:edit, :update, :destroy]
   
    
    def index
        
        @entry_open = Entry.where(status: 'en curso').reverse
        @entry_close = Entry.where(status: 'cerrada').reverse
    end

    def new
        @entry = Entry.new
    end

    def create
        @entry = Entry.new(entry_params)
        if @entry.save
            redirect_to root_path, notice: 'Entrada guardada'
        else
            redirect_to new_entries_path, alert: 'Entrada no guardada :c'
        end

    end


    def edit
    end

    def update
        @entry.update(entry_params)

       if @entry.save
            redirect_to root_path, notice: 'Entrada guardada'
        else
            redirect_to edit_entry_path, alert: 'Entrada no guardada :c'
        end
     end


     def destroy
        @entry.destroy
        redirect_to root_path, notice: 'El registro fue eliminado'
     end


    private 
    def entry_params
        params.require(:entry).permit(:title, :content, :status, :image_url)
    end

    def set_entries
        @entry = Entry.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |f| %>
    <div>
        <%= f.label :titulo %>
        <%= f.text_field :title %>
    </div>
    <br>
    <div>
        <%= f.label :contenido %>
        <%= f.text_area :content %>
    </div>
    <br>
    <div>
        <%= f.label :imagen %>
        <%= f.text_area :image_url %>
    </div>
    <br>
    <div>
        <%= f.label :estado %>
        <%= f.select :status, options_for_select(['en curso', 'cerrada']) %>
    </div>
    <br>
    <div>
        <%= f.submit 'Guardar'%>
    </div>
<%end%>

app/views/entries/edit.html.erb
<div class="container">
<br>
<br>
    <h2 class="font-weight-bolder text-monospace text-muted">Editar</h2>
<br>
<br>
    <div>
        <%= render 'form', entry: @entry  %> 
    </div>
</div>

app/views/entries/index.html.erb
<div class="container">
    <div class="table">
        <br>
        <br>
        <h1>Todas las entradas</h1>
        <hr>
        <h5 class="text-center">(No olvidar de correr el <strong>seed!</strong>) ;)</h5>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div>
            <h3>Entradas en curso</h3>

            <div>
                <table>
                    <thead>
                        <th>Fecha creación</th>
                        <th>Título</th>
                        <th>Contenido </th>
                        
                        <th>Imagen</th>
                    </thead>

                    <% @entry_open.each do |entry| %>
                    <tbody>
                        <th><%= entry.created_at %></th>
                        <th><%= entry.title %></th>
                        <th><%= entry.content %></th>
                       
                        <th><%= image_tag entry.image_url, style: 'height:50px;width:70px' %></th>
                        <th><%= link_to 'editar', edit_entry_path(entry) %></th>
                        <th><%= link_to 'eliminar', delete_entry_path(entry), method: :delete, data: {confirm: 'Seguro?'} %>
                        </th>
                    </tbody>
                    <% end %>
                </table>
            </div>
        </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>Entradas cerradas</h3>

        <div>
            <table>
                <thead>
                    <th>Fecha creación</th>
                    <th>Título</th>
                    <th>Contenido </th>
               
                    <th>Imagen</th>
                </thead>

                <% @entry_close.each do |entry| %>
                <tbody>
                    <th><%= entry.created_at %></th>
                    <th><%= entry.title %></th>
                    <th><%= entry.content %></th>
                   
                    <th><%= image_tag entry.image_url, style: 'height:50px;width:70px' %></th>
                    <th><%= link_to 'editar', edit_entry_path(entry) %></th>
                    <th><%= link_to 'eliminar', delete_entry_path(entry), method: :delete, data: {confirm: 'Seguro?'} %>
                    </th>
                </tbody>
                <% end %>
            </table>
        </div>
    </div>
    <br>
    <br>
    <%= link_to 'Nueva entrada', new_entries_path, class:"btn btn-outline-primary font-weight-bolder text-decoration-none" %>
</div>
<br>
<br>

app/views/entries/new.html.erb
<div class="container">
<br>
<br>
    <h2 class="font-weight-bolder text-monospace text-muted">Nueva entrada</h2>
<br>
<br>
    <div>
        <%= render 'form', entry: @entry  %> 
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light py-4 pl-4 font-weight-bold">
    <%= link_to 'HOME', root_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="#"> <span class="sr-only">(current)</span></a>
      </div>
    </div>
  </nav>
  <%= notice %>
  <%= alert %>
  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>
</html>